language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t ctsubaki/docker-react -f Dockerfile.dev .

script:
  - docker run ctsubaki/docker-react npm run test -- --coverage

