language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t ctsubaki/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ctsubaki/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: “us-west-2”
  app: “docker”
  env: “Docker-env”
  bucker_name: “elasticbeanstalk-us-west-2-469989652599”
  bucket_path: “docker”
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: “$AWS_SECRET_KEY”

